### PR TITLE
Custom path to specify where the markdowns are stored

### PR DESCRIPTION
**Pull request by shubham-cpp**
Hi, looked at your plugin kinda great idea. Added the feature to specify custom path. I gave a generic name you can change it. I also updated readme to provide instruction on how to configure custom path

### CODE REVIEW

**Comment by weizheheng** [comment]
Hi @shubham-cpp , thank you so much for your PR and interest in this plugin. I was looking at something similar for adding support for user to define their own path to store the workbench path. My concern that time was, if they put in some path that does not exist, do I want to create it for them. But I think for now its fine, I tested locally, error message will be shown, if they put in some path that does not exists, which is fine for me now.
image

- Can you squash your commit and maybe remove the unnecessary line? We should focus this PR only on adding support for custom path.

**Comment by shubham-cpp** [comment]
Ok I'll do that(I was trying out something different). Also this maybe unnecessary but we could add a function for asking users to create directory if it doesn't exists already.

**Comment by weizheheng** [comment]
The PR looks good to me, do you mind squashing your commit into just one? Then after I have tested it locally, I will merge it in. Thanks again!

**Comment by shubham-cpp** [comment]
Yes cleaned up already like an hour ago. Currently working on a code to create directory if it doesn't exists

**Comment by shubham-cpp** [comment]
I have got a working code to create dir if doesn't exists, should I update?

**Comment by shubham-cpp** [comment]
I thunk i messed up the squashes. Check if this works or else I'll create a new PR with create directory if default_path doesn't exists.

**Comment by weizheheng** [comment]
@shubham-cpp So sorry for the late reply, been busy with work.  I think you misunderstand my meaning of [squashing the commit](https://gitbetter.substack.com/p/how-to-squash-git-commits). But yeah, I have already implemented your code into my local branch, I will deploy some new features up later today. After using this plugin for a week in my day-to-day life, I feel like there is a need for branch-specific workbenches. So right now, user will have a project workbench and also branch specific workbench. I have also cleaned up the code for a bit (I hope). Last but not least, I really appreciate you spending time working on this, let me know if you have any good ideas that you think might be a good fit for this plugin :)
Cheers and have a great day!

**Pull request closed without merging**
